# title: DevOps Blog
theme: minima
author:
  name: Bikarna Pokharel
  email: "bikarnap@gmail.com"
minima:
  date_format: "%b %-d, %Y"
lang: en
timezone: Europe/Helsinki
twitter_username: bikarnap
github_username: bikarnap
linkedin_username: bikarnap


