# title: DevOps Blog
# Old:
theme: minima

# New:
remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

include:
  # - _includes/head-custom.html

author:
  name: Bikarna Pokharel
  email: "bikarnap@gmail.com"
minima:
  date_format: "%b %-d, %Y"
lang: en
timezone: Europe/Helsinki
twitter_username: bikarnap
github_username: bikarnap
linkedin_username: bikarna-pokharel-40443652


